version: '3'
services:
        docker-mysql-new:
          restart: always
          # container_name: docker-mysql
          image: mysql
          environment: 
          #  MYSQL_DATABASE: shopping_site
            MYSQL_ROOT_PASSWORD: root
            # MYSQL_ROOT_HOST: '%'
          volumes:
            - db_data:/var/lib/mysql
          ports:
            - "6033:3306"
volumes:
    db_data:        
           
